package com.fifa.model;
// Generated 5 Jun, 2018 2:54:13 PM by Hibernate Tools 5.2.6.Final

import java.math.BigInteger;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BetResult generated by hbm2java
 */
@Entity
@Table(name = "betResult", schema = "fifa2018")
public class BetResult implements java.io.Serializable {

	private static final long serialVersionUID = -4536805821822065402L;
	
	@Id
	private BigInteger userId;
	
	private Long won;
	
	private Long lost;
	
	private Long draw;

	public BigInteger getUserId() {
		return userId;
	}

	public void setUserId(BigInteger userId) {
		this.userId = userId;
	}

	public Long getWon() {
		return won;
	}

	public void setWon(Long won) {
		this.won = won;
	}

	public Long getLost() {
		return lost;
	}

	public void setLost(Long lost) {
		this.lost = lost;
	}

	public Long getDraw() {
		return draw;
	}

	public void setDraw(Long draw) {
		this.draw = draw;
	}

	@Override
	public String toString() {
		return "BetResult [userId=" + userId + ", won=" + won + ", lost=" + lost + ", draw=" + draw + "]";
	}

}