package com.fifa.model;
// Generated 5 Jun, 2018 2:54:13 PM by Hibernate Tools 5.2.6.Final

import java.math.BigInteger;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bet generated by hbm2java
 */
@Entity
@Table(name = "customBet", schema = "fifa2018")
public class CustomBet implements java.io.Serializable {

	private static final long serialVersionUID = -3393874239386684404L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private BigInteger betId;
	
	private BigInteger matchId;
	
	private String betDesc;
	
	@Temporal(TemporalType.TIMESTAMP)
	private Date validityFrom;
	
	@Temporal(TemporalType.TIMESTAMP)
	private Date validityUpto;
	
	private BigInteger startedByUserId;
	
	private String betResultCode;
	
	public BigInteger getBetId() {
		return betId;
	}

	public void setBetId(BigInteger betId) {
		this.betId = betId;
	}

	public String getBetDesc() {
		return betDesc;
	}

	public void setBetDesc(String betDesc) {
		this.betDesc = betDesc;
	}

	public Date getValidityFrom() {
		return validityFrom;
	}

	public void setValidityFrom(Date validityFrom) {
		this.validityFrom = validityFrom;
	}

	public Date getValidityUpto() {
		return validityUpto;
	}

	public void setValidityUpto(Date validityUpto) {
		this.validityUpto = validityUpto;
	}

	public BigInteger getStartedByUserId() {
		return startedByUserId;
	}

	public void setStartedByUserId(BigInteger startedByUserId) {
		this.startedByUserId = startedByUserId;
	}

	public BigInteger getMatchId() {
		return matchId;
	}

	public void setMatchId(BigInteger matchId) {
		this.matchId = matchId;
	}
	
	public String getBetResultCode() {
		return betResultCode;
	}
	
	public void setBetResultCode(String betResultCode) {
		this.betResultCode = betResultCode;
	}

	@Override
	public String toString() {
		return "CustomBet [betId=" + betId + ", matchId=" + matchId + ", betDesc=" + betDesc + ", validityFrom="
				+ validityFrom + ", validityUpto=" + validityUpto + ", startedByUserId=" + startedByUserId
				+ ", betResultCode=" + betResultCode + "]";
	}

}