package com.fifa.model;
// Generated 5 Jun, 2018 2:54:13 PM by Hibernate Tools 5.2.6.Final

import java.math.BigInteger;
import java.util.Date;

import javax.persistence.Cacheable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.fifa.appcode.FifaTeam;
import com.fifa.appcode.UserBetStatus;

/**
 * FifaMatches generated by hbm2java
 */
@Entity
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
@Table(name = "fifaMatch", schema = "fifa2018")
public class FifaMatch implements java.io.Serializable {

	private static final long serialVersionUID = 2045854164384126340L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private BigInteger fifaMatchId;
	
	private String team1Code;
	
	private BigInteger team1Id;
	
	private String team1Group;
	
	private String team2Code;
	
	private BigInteger team2Id;
	
	private String team2Group;
	
	@Temporal(TemporalType.TIMESTAMP)
	private Date matchDateTime;
	
	private String venue;
	
	private String winnerTeamCode;

	private String result;
	
	@Transient
	private String team1Logo;
	
	@Transient
	private String team2Logo;
	
	@Transient
	private String team1Name;
	
	@Transient
	private String team2Name;
	
	@Transient
	private String betTeamCode;
	
	@Transient
	private UserBetStatus userBetStatus;

	public BigInteger getFifaMatchId() {
		return fifaMatchId;
	}

	public void setFifaMatchId(BigInteger fifaMatchId) {
		this.fifaMatchId = fifaMatchId;
	}

	public String getTeam1Code() {
		for(FifaTeam t : FifaTeam.values())
			if(t.getCode().equals(this.team1Code))
				this.team1Name = t.toString();
		return team1Code;
	}

	public void setTeam1Code(String team1Code) {
		this.team1Code = team1Code;
	}

	public BigInteger getTeam1Id() {
		return team1Id;
	}

	public void setTeam1Id(BigInteger team1Id) {
		this.team1Id = team1Id;
	}

	public String getTeam1Group() {
		return team1Group;
	}

	public void setTeam1Group(String team1Group) {
		this.team1Group = team1Group;
	}

	public String getTeam2Code() {
		for(FifaTeam t : FifaTeam.values())
			if(t.getCode().equals(this.team2Code))
				this.team2Name = t.toString();
		return team2Code;
	}

	public void setTeam2Code(String team2Code) {
		this.team2Code = team2Code;
	}

	public BigInteger getTeam2Id() {
		return team2Id;
	}

	public void setTeam2Id(BigInteger team2Id) {
		this.team2Id = team2Id;
	}

	public String getTeam2Group() {
		return team2Group;
	}

	public void setTeam2Group(String team2Group) {
		this.team2Group = team2Group;
	}

	public Date getMatchDateTime() {
		return matchDateTime;
	}

	public void setMatchDateTime(Date matchDateTime) {
		this.matchDateTime = matchDateTime;
	}

	public String getVenue() {
		return venue;
	}

	public void setVenue(String venue) {
		this.venue = venue;
	}

	public String getWinnerTeamCode() {
		return winnerTeamCode;
	}
	
	public void setWinnerTeamCode(String winnerTeamCode) {
		this.winnerTeamCode = winnerTeamCode;
	}
		
	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getTeam1Logo() {
		return team1Logo;
	}
	
	public void setTeam1Logo(String team1Logo) {
		this.team1Logo = team1Logo;
	}
	
	public String getTeam2Logo() {
		return team2Logo;
	}
	
	public void setTeam2Logo(String team2Logo) {
		this.team2Logo = team2Logo;
	}
	
	public String getTeam1Name() {
		return team1Name;
	}
	
	public void setTeam1Name(FifaTeam team1Name) {
		this.team1Name = team1Name.toString();
	}
	
	public String getTeam2Name() {
		return team2Name;
	}
	
	public void setTeam2Name(FifaTeam team2Name) {
		this.team2Name = team2Name.toString();
	}
	
	public String getBetTeamCode() {
		return betTeamCode;
	}
	
	public void setBetTeamCode(String betTeamCode) {
		this.betTeamCode = betTeamCode;
	}
	
	public UserBetStatus getUserBetStatus() {
		return userBetStatus;
	}
	
	public void setUserBetStatus(UserBetStatus userBetStatus) {
		this.userBetStatus = userBetStatus;
	}
	
	@Override
	public String toString() {
		return "FifaMatch [fifaMatchId=" + fifaMatchId + ", team1Code=" + team1Code + ", team1Id=" + team1Id
				+ ", team1Group=" + team1Group + ", team2Code=" + team2Code + ", team2Id=" + team2Id + ", team2Group="
				+ team2Group + ", matchDateTime=" + matchDateTime + ", venue=" + venue + ", winnerTeamCode="
				+ winnerTeamCode + ", result=" + result + "]";
	}
	
}
