package com.fifa.model;
// Generated 5 Jun, 2018 2:54:13 PM by Hibernate Tools 5.2.6.Final

import java.math.BigInteger;
import java.util.Arrays;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.fifa.appcode.FifaBlobType;

/**
 * Blob generated by hbm2java
 */
@Entity
@Cacheable
@org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "fifaBlob", schema = "fifa2018")
public class FifaBlob implements java.io.Serializable {

	private static final long serialVersionUID = -5713811589857305395L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private BigInteger blobId;
	
	@Column(name = "blobType")
	private FifaBlobType type;
	
	private String teamCode;
	
	@Lob
	@Column(name = "blobData")
	private byte[] data;

	public BigInteger getBlobId() {
		return blobId;
	}

	public void setBlobId(BigInteger blobId) {
		this.blobId = blobId;
	}

	public FifaBlobType getType() {
		return type;
	}

	public void setType(FifaBlobType type) {
		this.type = type;
	}

	public String getTeamCode() {
		return teamCode;
	}

	public void setTeamCode(String teamCode) {
		this.teamCode = teamCode;
	}

	public byte[] getData() {
		return data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	@Override
	public String toString() {
		return "FifaBlob [blobId=" + blobId + ", type=" + type + ", teamCode=" + teamCode + ", data="
				+ Arrays.toString(data) + "]";
	}
	
}
