package com.fifa.model;
// Generated 5 Jun, 2018 2:54:13 PM by Hibernate Tools 5.2.6.Final

import java.math.BigInteger;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fifa.appcode.FifaGroup;
import com.fifa.appcode.FifaTeam;

/**
 * Team generated by hbm2java
 */
@Entity
@Table(name = "team", schema = "fifa2018")
public class Team implements java.io.Serializable {

	private static final long serialVersionUID = 5929711931299278342L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private BigInteger teamId;
	
	@Enumerated(EnumType.STRING)
	private FifaTeam teamName;
	
	private String teamCode;
	
	private FifaGroup teamGroup;
	
	private Integer matchesPlayed;
	
	private Integer won;
	
	private Integer draw;
	
	private Integer lost;
	
	private Integer goalsFor;
	
	private Integer goalsAgainst;
	
	private Integer goalDiff;
	
	private Double points;
	
	private BigInteger flagBlobId;
	
	public Team() {
		draw = 0;
		matchesPlayed = 0;
		won = 0;
		lost = 0;
		goalsFor = 0;
		goalsAgainst = 0;
		goalDiff = 0;
		points = 0D;
	}

	public BigInteger getTeamId() {
		return teamId;
	}

	public void setTeamId(BigInteger teamId) {
		this.teamId = teamId;
	}

	public FifaTeam getTeamName() {
		return teamName;
	}

	public void setTeamName(FifaTeam teamName) {
		this.teamName = teamName;
		this.teamCode = teamName.getCode();
	}

	public FifaTeam getTeamCode() {
		for(FifaTeam ft : FifaTeam.values())
			if(ft.getCode().equals(this.teamCode))
				return ft;
			return null;
	}

	public void setTeamCode(FifaTeam teamCode) {
		this.teamCode = teamCode.getCode();
	}

	public FifaGroup getTeamGroup() {
		return teamGroup;
	}

	public void setTeamGroup(FifaGroup teamGroup) {
		this.teamGroup = teamGroup;
	}

	public Integer getMatchesPlayed() {
		return matchesPlayed;
	}

	public void setMatchesPlayed(Integer matchesPlayed) {
		this.matchesPlayed = matchesPlayed;
	}

	public Integer getWon() {
		return won;
	}

	public void setWon(Integer won) {
		this.won = won;
	}

	public Integer getDraw() {
		return draw;
	}

	public void setDraw(Integer draw) {
		this.draw = draw;
	}

	public Integer getLost() {
		return lost;
	}

	public void setLost(Integer lost) {
		this.lost = lost;
	}

	public Integer getGoalsFor() {
		return goalsFor;
	}

	public void setGoalsFor(Integer goalsFor) {
		this.goalsFor = goalsFor;
	}

	public Integer getGoalsAgainst() {
		return goalsAgainst;
	}

	public void setGoalsAgainst(Integer goalsAgainst) {
		this.goalsAgainst = goalsAgainst;
	}

	public Integer getGoalDiff() {
		return goalDiff;
	}

	public void setGoalDiff(Integer goalDiff) {
		this.goalDiff = goalDiff;
	}

	public Double getPoints() {
		return points;
	}

	public void setPoints(Double points) {
		this.points = points;
	}

	public BigInteger getFlagBlobId() {
		return flagBlobId;
	}

	public void setFlagBlobId(BigInteger flagBlobId) {
		this.flagBlobId = flagBlobId;
	}

	@Override
	public String toString() {
		return "Team [teamId=" + teamId + ", teamName=" + teamName + ", teamCode=" + teamCode + ", teamGroup=" + teamGroup
				+ ", matchesPlayed=" + matchesPlayed + ", won=" + won + ", draw=" + draw + ", lost=" + lost
				+ ", goalsFor=" + goalsFor + ", goalsAgainst=" + goalsAgainst + ", goalDiff=" + goalDiff + ", points="
				+ points + ", flagBlobId=" + flagBlobId + "]";
	}
	
}