package com.fifa.model;
// Generated 5 Jun, 2018 2:54:13 PM by Hibernate Tools 5.2.6.Final

import java.math.BigInteger;

import javax.persistence.Cacheable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.fifa.appcode.UserBetStatus;

/**
 * UserBet generated by hbm2java
 */
@Entity
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "userBet", schema = "fifa2018")
public class UserBet implements java.io.Serializable {

	private static final long serialVersionUID = 3853063590925105086L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private BigInteger keyId;
	
	private BigInteger betId;
	
	private BigInteger matchId;
	
	private BigInteger userId;
	
	private String betCode;
	
	private UserBetStatus userBetStatus;
	
	@Transient
	private String betDesc;
	
	@Transient
	private String betCodeDesc;
	
	public UserBet() {
		this.userBetStatus = UserBetStatus.UNDEFINED;
	}
	
	public BigInteger getKeyId() {
		return keyId;
	}
	
	public void setKeyId(BigInteger keyId) {
		this.keyId = keyId;
	}
	
	public BigInteger getBetId() {
		return betId;
	}

	public void setBetId(BigInteger betId) {
		this.betId = betId;
	}

	public BigInteger getMatchId() {
		return matchId;
	}

	public void setMatchId(BigInteger matchId) {
		this.matchId = matchId;
	}

	public BigInteger getUserId() {
		return userId;
	}

	public void setUserId(BigInteger userId) {
		this.userId = userId;
	}

	public String getBetCode() {
		return betCode;
	}

	public void setBetCode(String betCode) {
		this.betCode = betCode;
	}
	
	public String getBetDesc() {
		return betDesc;
	}
	
	public void setBetDesc(String betDesc) {
		this.betDesc = betDesc;
	}

	public String getBetCodeDesc() {
		return betCodeDesc;
	}
	
	public void setBetCodeDesc(String betCodeDesc) {
		this.betCodeDesc = betCodeDesc;
	}
	
	public UserBetStatus getUserBetStatus() {
		return userBetStatus;
	}

	public void setUserBetStatus(UserBetStatus userBetStatus) {
		this.userBetStatus = userBetStatus;
	}

	@Override
	public String toString() {
		return "UserBet [keyId=" + keyId + ", betId=" + betId + ", matchId=" + matchId + ", userId=" + userId
				+ ", betCode=" + betCode + "]";
	}
	
}