package com.fifa.model;
// Generated 5 Jun, 2018 2:54:13 PM by Hibernate Tools 5.2.6.Final

import java.math.BigInteger;

import javax.persistence.Cacheable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * User generated by hbm2java
 */
@Entity
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Table(name = "user", schema = "fifa2018")
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 48125929581796647L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private BigInteger userId;
	
	@JsonIgnore
	private BigInteger proPicId;
	
	private String name;
	
	private String mobileNo;
	
	@JsonIgnore
	private String password;
	
	@Transient
	private String profilePic;

	public BigInteger getUserId() {
		return userId;
	}

	public void setUserId(BigInteger userId) {
		this.userId = userId;
	}

	public BigInteger getProPicId() {
		return proPicId;
	}

	public void setProPicId(BigInteger proPicId) {
		this.proPicId = proPicId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getProfilePic() {
		return profilePic;
	}
	
	public void setProfilePic(String profilePic) {
		this.profilePic = profilePic;
	}

	@Override
	public String toString() {
		return "User [userId=" + userId + ", proPicId=" + proPicId + ", name=" + name + ", mobileNo=" + mobileNo
				+ ", password=" + password + "]";
	}
	
}